### ISSUE TITLE
Movie example not working

### ISSUE THREAD

**Issue by BeSweets** [nmcassa/letterboxdpy#11]
Just using the code in the movie example in the readme:

```
from letterboxdpy import movie
king = Movie("king kong")
print(king)
king = Movie("king kong", 2005)
print(king)
house = Movie("/film/the-house-2022-1/")
print(house)
```

I get:

```
Traceback (most recent call last):
  File "/Users/bs/Sites/Letterblocksd/Scripts/newScraper/BeScrapes.py", line 2, in <module>
    king = Movie("king kong")
           ^^^^^
NameError: name 'Movie' is not defined. Did you mean: 'movie'?
```
I believe the readme should have movie.Movie

**Comment by nmcassa** [comment]
You're right this is a mistake. I believe it should be movie.Movie() as seen in other examples. Let me know if they works for you.

**Comment by BeSweets** [comment]
I just edited my post not seeing that you had already responded!  Thanks for the quick response
