### ISSUE TITLE
parser library not found

### ISSUE THREAD

**Issue by NilayGaitonde** [nmcassa/letterboxdpy#19]
Hey! 
Firstly i'd like to sat that this seems to be a great project but I am getting an FeatureNotFoundError while trying to run the code
<img width="1354" alt="Screenshot 2024-01-23 at 20 04 17" src="https://github.com/nmcassa/letterboxdpy/assets/68230775/a8ebc6b2-eac0-4b73-9132-72943685154a">

I have installed bs4 and lxml
<img width="572" alt="Screenshot 2024-01-23 at 20 06 10" src="https://github.com/nmcassa/letterboxdpy/assets/68230775/8167825a-7ab4-4c0a-b5f1-c31d977cfa40">
<img width="568" alt="Screenshot 2024-01-23 at 20 06 33" src="https://github.com/nmcassa/letterboxdpy/assets/68230775/0be48b73-41b5-430e-9ec7-342fcbb40529">

It would be a great if you could help me with this!!

**Comment by nmcassa** [comment]
Hey, I haven't run into this problem. This is all I can find: https://stackoverflow.com/questions/24398302/bs4-featurenotfound-couldnt-find-a-tree-builder-with-the-features-you-requeste

Hopefully that helps.

**Comment by NilayGaitonde** [comment]
Hey! According to the stackerflow answers it could be an version error in python which doesn't seem to be the case as I have created a new venv using conda (with python 3.10)
<img width="485" alt="Screenshot 2024-01-23 at 20 28 51" src="https://github.com/nmcassa/letterboxdpy/assets/68230775/bb4e29d4-8da5-4be5-8099-820b9ee9731c">
I have pip installed lxml as well yet the error persists

**Comment by FastFingertips** [comment]
Did you solve the problem? @NilayGaitonde
