### ISSUE TITLE
can't find users

### ISSUE THREAD

**Issue by francescabudel** [nmcassa/letterboxdpy#9]
Hello, I've used letterboxdpy in the past with no issues at all, but just to gather data about movies. 

I'm tying now to do the same with users, but I keep getting the errors  ''NoneType object has no attribute 'text'' and then  'No user found', even when using the example provided in the readme.md.

`from letterboxdpy import user`
`nick = user.User("nmcassa")`
`print(nick)`

these are the errors I get: 

![Screenshot 2023-11-23 155850](https://github.com/nmcassa/letterboxdpy/assets/92512623/b05b23d7-ce83-4a58-bdfb-f8ee36a4a40d)

Thank you in advance.

**Comment by saadpocalypse** [comment]
I am not the creator of this library but here is the solution.

In the `user.py` module, go to line number 63.
```
data = page.find("span", {"class": ["watchlist-count"], }) 
```

The span's class is not watchlist-count, but js-watchlist-count. Replacing the line with:
```
data = page.find("span", {"class": ["js-watchlist-count"], })
```
will fix the issue.

**Comment by francescabudel** [comment]
Thank you to the both of you. I've applied your suggestions and it works perfectly now!
